---
title: "Weekly report of animal performance"

subtitle: "(**protocol**: sound categorization, **experimenter**: `r params$exp_SC`)"

output: pdf_document


params:
  exp_SC: NA
  stg_SC: NA
  fil_SC: NA
  ani_SC: NA
  dt_SC: NA
  
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage[normalem]{ulem}
  - \usepackage[utf8]{inputenc}
  - \usepackage{makecell}
  - \usepackage{xcolor}  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(knitr)
library(kableExtra)

```

# Summary of last 5 day's performance

```{r}
TRAINING %>%
            dplyr::filter(
              experimenter == params$exp_SC,
              choice_direction == "right_trials",
              protocol == "@SoundCategorization",
              date <= max(date), date > max(date)-4
            ) %>%
  mutate(correct_ratio = (correct_trials / completed_trials) %>%
           round(2)) %>%
  mutate(violation_ratio = (violation_trials / all_trials) %>%
              round(2)) %>% 
  select(
    animal_id,
    date,
    stage,
    correct_trials,
    error_trials,
    violation_trials,
    timeoout_trials,
    correct_ratio,
    violation_ratio
    ) %>% 
  dplyr::group_by("Animal" = animal_id) %>% 
  dplyr::summarise(
    "Mean correct" = paste0(
      mean(correct_trials) %>% round(2),
      " ", intToUtf8(177), " ",    
      sd(correct_trials) %>% round(2)),
    "Mean error" = paste0(
      mean(error_trials) %>% round(2),
      " ", intToUtf8(177), " ",
      sd(error_trials)%>% round(2)),
    "Mean violation" = paste0(
      mean(violation_trials) %>% round(2),
      " ", intToUtf8(177), " ",
      sd(violation_trials) %>% round(2)),
    "Mean timeoout" = paste0(
      mean(timeoout_trials) %>% round(2),
      " ", intToUtf8(177), " ",
      sd(timeoout_trials) %>% round(2)),
    "Mean correct ratio" = paste0(
      mean(correct_ratio) %>% round(2),
      " ", intToUtf8(177), " ",
      sd(correct_ratio) %>% round(2)),
    "Mean violation ratio" = paste0(
      mean(violation_ratio) %>% round(2),
      " ", intToUtf8(177), " ",
      sd(violation_ratio) %>% round(2)
      )
    ) %>% 
  knitr::kable(format = "latex", booktabs = T) %>% 
  kable_styling(latex_options = c("scale_down", "striped"))
```



# Number of completed trials

```{r, fig.width=12, fig.height=10}
 plots_SoundCateg(
      plottype_SC = "No. completed trials",
      #datelim_SC = params$dt,
      stage_filter_SC = params$stg_SC,
      f_options_SC = params$fil_SC,
      animal_filter_SC = params$ani_SC,
      exp_SC = params$exp_SC
    )
```

# Number of correct trials

```{r, fig.width=12, fig.height=10}
 plots_SoundCateg(
      plottype_SC = "No. correct trials",
      #datelim_SC = params$dt,
      stage_filter_SC = params$stg_SC,
      f_options_SC = params$fil_SC,
      animal_filter_SC = params$ani_SC,
      exp_SC = params$exp_SC
    )
```




# Ratio of correct trials

```{r, fig.width=12, fig.height=10}
 plots_SoundCateg(
      plottype_SC = "Correct ratio",
      #datelim_SC = params$dt,
      stage_filter_SC = params$stg_SC,
      f_options_SC = params$fil_SC,
      animal_filter_SC = params$ani_SC,
      exp_SC = params$exp_SC
    )
```
